<?php
/**
 * @file
 * Code for the Caroneiros Review feature.
 */

include_once 'caroneiros_review.features.inc';

/**
 * Implements hook_menu().
 */
function caroneiros_review_menu() {
    $items = array();

    $items['user/%user/review'] = array(
        'title' => t('Avaliação'),
        'page callback' => 'caroneiros_review_form',
        'page arguments' => array(1),
        'access callback' => 'user_is_logged_in',
        'file' => 'caroneiros_review.pages.inc',
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_preprocess_node().
 */
 function caroneiros_review_preprocess_node(&$variables) {
    if ($variables['type'] == 'carona') {
        global $user;
        $nid = $variables['nid'];
        $account = user_load($variables['uid']);
        $name = $account->field_nome[LANGUAGE_NONE][0]['value'];

        $query = new EntityFieldQuery();
        $ids = $query->entityCondition('entity_type', 'node')
                ->entityCondition('bundle', 'review')
                ->propertyCondition('status', 1)
                ->fieldCondition('field_user', 'target_id', $account->uid)
                ->execute();

        $nodes = array();
        if (!empty($ids)) {
            $nodes = node_load_multiple(array_keys($ids['node']));
            $sum = 0;
            foreach ($nodes as $node) {
                $sum += $node->field_rating[LANGUAGE_NONE][0]['rating'];
            }

            $mean = $sum/count($nodes);
            $variables['fivestar'] = array(
                '#theme' => 'fivestar_static',
                '#rating' => $mean,
                '#stars' => 5,
                '#tag' => 'rating',
                '#widget' => array(
                    'name' => 'whatever',
                    'css' => '',
                ),

            );
        }
    }
}

function caroneiros_review_theme() {
  $items = array();
    
  $items['review_node_form'] = array(
    'render element' => 'form',
    'path' => drupal_get_path('theme', 'bootstrap') . '/boostrap_subtheme/templates',
    'template' => 'review-node-form',
  );
  return $items;
}

function caroneiros_review_preprocess_user_profile(&$variables) {
    global $user;
    if($user->uid != arg(1)) {
        $uid = arg(1);
        $variables['review'] = array(
            '#markup' => l(
                'Avalie este usuário', 
                "user/$uid/review",
                array(
                    'query' => array('destination' => current_path()),
                    'attributes' => array('class' => array('btn', 'btn-info')),
                    'html' => TRUE,
                )
            ),
            '#attached' => array(
                'css' => array(
                    drupal_get_path('module', 'caroneiros_review') . '/css/caroneiros_review.css',
                ),
            ),
        );
        
    
    }
    
    foreach ($variables['user_profile'] as $key => $value) {
        $variables[$key] = $value;
    }
}

function caroneiros_review_node_insert($node) {
    //dpm($node);
}