<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function caroneiros_usuario_form_user_register_form_alter(&$form, &$form_state) {
    //dpm($form);

    // Aplica um máscara no campo CPF
    //$form['field_cpf'][LANGUAGE_NONE][0]['value']['#mask'] = '999.999.999-99';
    //$form['field_cpf'][LANGUAGE_NONE][0]['value']['#process'] = array('masked_input_process_callback');

    // Adiciona um funcao de validacao do formulario
    //$form['#validate'][] = 'caroneiros_usuario_form_user_register_form_alter_validate';
}

/**
 * Validate callback.
 */
function caroneiros_usuario_form_user_register_form_alter_validate($form, $form_state) {
    $cpf = $form_state['values']['field_cpf'][LANGUAGE_NONE][0]['value'];

    if (!caroneiros_usuario_valid_cpf($cpf)) {
        form_set_error('field_cpf', t('Invalid CPF'));
    }
}

function caroneiros_usuario_theme() {
  $items = array();
    
  $items['user_login'] = array(
    'render element' => 'form',
    'path' => drupal_get_path('theme', 'bootstrap') . '/boostrap_subtheme/templates',
    'template' => 'user-login',
  );
  $items['user_register_form'] = array(
    'render element' => 'form',
    'path' => drupal_get_path('theme', 'bootstrap') . '/boostrap_subtheme/templates',
    'template' => 'user-register-form',
  );
  $items['user_pass'] = array(
    'render element' => 'form',
    'path' => drupal_get_path('theme', 'bootstrap') . '/boostrap_subtheme/templates',
    'template' => 'user-pass',
  );
  return $items;
}