<?php
/**
 * @file
 * Drupal needs this blank file.
 */
 
/**
 * Implements hook_form_FORM_ID_alter().
 */
function caroneiros_fale_conosco_form_alter(&$form, &$form_state,$form_id) {
//    dpm($form);
//    dpm($form_id);
//    id do formulario: webform_client_form_2

    // Aplica um máscara no campo telefone
    $form['submitted']['telefone']['#mask'] = '(99)99999 9999';
//TODO arrumar mascara
    $form['submitted']['telefone']['#process'] = array('masked_input_process_callback');


//  TODO Validar e-mail
    
}
    