<?php
/**
 * @file
 * Code for the Caroneiros: Orcamento feature.
 */

include_once 'caroneiros_orcamento.features.inc';
 

/**
  * Implements hook_theme_registry_alter().
  */
function caroneiros_fale_conosco_theme_registry_alter(&$theme_registry) {
    $nid = variable_get('caroneiros_fale_conosco_webform', 0);
    if ($nid) {
        $theme_registry['webform_form_' . $nid] = array(
            'render element' => 'form',
            'template' => 'sites/all/themes/bootstrap/bootstrap_subtheme/templates/webform-form--contato',
            'type' => 'module',
            'theme path' => 'sites/all/themes/bootstrap/bootstrap_subtheme',
            'preprocess functions' => array(),
            'process functions' => array(),
        );
    }
    
    $nid = variable_get('caroneiros_orcamento_webform', 0);
    if ($nid) {
        $theme_registry['webform_form_' . $nid] = array(
            'render element' => 'form',
            'template' => 'sites/all/themes/bootstrap/bootstrap_subtheme/templates/webform-form--orcamento',
            'type' => 'module',
            'theme path' => 'sites/all/themes/bootstrap',
            'preprocess functions' => array(),
            'process functions' => array(),
        );
    }
}